# Generated by Django 3.2.3 on 2021-06-13 11:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('odoc', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='docplace',
            name='File',
            field=models.TextField(max_length=3000),
        ),
    ]
