# Generated by Django 3.2.3 on 2021-06-12 10:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rapi', '0002_router_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='router',
            name='type',
            field=models.CharField(max_length=4),
        ),
    ]
